{% set name = "qe-tools" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/qe-tools-{{ version }}.tar.gz
  sha256: 2b7dc5aa7ec64956476ff768c6faaf33d48d6db2e1fdbfaf16497ec1b8dd1da0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - flit >=3.4,<4
    - pip
    - python >=3.6
  run:
    - numpy
    - packaging
    - python >=3.6
    - scipy

test:
  imports:
    - qe_tools
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aiidateam/qe-tools
  summary: A set of useful tools to manage Quantum ESPRESSO files
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - chrisjsewell
